mongo/pom.xml
mongo/src/main/java/org/craftercms/commons/mongo/MongoClientFactory.java
mongo/src/main/java/org/craftercms/commons/mongo/MongoScriptRunner.java

http://wiki.craftercms.org/pages/viewpage.action?pageId=3867032#CrafterProfile/SocialExpress-InstallationInstructions-MongoDbconfigurationanddatabootstrappingGreen2.5.1onwards

CRAFTERCMS-1446 MongoScriptRunner is using eval to execute scripts

---

mongo/src/main/java/org/craftercms/commons/mongo/MongoClientFromUriFactoryBean.java
mongo/src/main/java/org/craftercms/commons/mongo/MongoScriptRunner.java

Make sure that if running all from a directory respects filename order.

---

utilities/src/main/java/org/craftercms/commons/rest/OkResult.java
utilities/src/main/java/org/craftercms/commons/validation/ValidationException.java
utilities/src/main/java/org/craftercms/commons/validation/ValidationResult.java

Changes to validation classes.
Added OkResult class.

Small changes

---

utilities/src/main/java/org/craftercms/commons/http/HttpUtils.java
utilities/src/main/java/org/craftercms/commons/rest/BaseRestExceptionHandlers.java

* Added new util methods used commonly by REST clients.

New util methods

---

mongo/src/main/java/org/craftercms/commons/mongo/UpdateHelper.java

Added new method to handle embedded documents in update

---

utilities/src/main/java/org/craftercms/commons/rest/LoggingRequestInterceptor.java

* Added LoggingRequestInterceptor.

New utility class added:

---

pom.xml

* Updated Commons Bean Utils version to 1.9.3 to fix issue with Commons Configuration.

Updated dependency version:

---

utilities/src/main/java/org/craftercms/commons/crypto/SimpleDigest.java
utilities/src/main/java/org/craftercms/commons/crypto/impl/EncryptionTool.java

* Added options for encoding/decoding in Base 64.

Encryption tool enhancement

---

mongo/src/main/java/org/craftercms/commons/mongo/AbstractJongoRepository.java
mongo/src/main/java/org/craftercms/commons/mongo/JongoFactoryBean.java
mongo/src/main/java/org/craftercms/commons/mongo/MongoClientOptionsFactory.java
mongo/src/main/java/org/craftercms/commons/mongo/MongoScriptRunner.java
pom.xml

Notes:
Jongo does not fully support 3.x API of mongodriver
so lots of warnings will be thrown for using deprecated
api, this should be fix in Jongo 1.4

Solve 1278.

---

aws/pom.xml
pom.xml

* Added new AWS Commons module.

New module:

---

validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateDoubleParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateIntegerParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateLongParam.java
validation/src/main/java/org/craftercms/commons/validation/validators/ErrorCodes.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/AbstractNumberValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/AnnotationBasedValidatorFactoryRegistry.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/DoubleParamValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/DoubleValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/IntegerParamValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/IntegerValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/LongParamValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/LongValidator.java
validation/src/main/resources/crafter/commons/validation/errors.properties

* Added validators for Integer, Long and Double.

Added validators:

---

utilities/src/main/java/org/craftercms/commons/config/DecryptionLookup.java
utilities/src/main/java/org/craftercms/commons/config/YamlConfiguration.java
utilities/src/main/java/org/craftercms/commons/crypto/CryptoException.java
utilities/src/main/java/org/craftercms/commons/crypto/SimpleCipher.java
utilities/src/main/java/org/craftercms/commons/crypto/SimpleDigest.java
utilities/src/main/java/org/craftercms/commons/crypto/impl/NoOpTextEncryptor.java
utilities/src/main/java/org/craftercms/commons/exceptions/DateParseException.java
utilities/src/main/java/org/craftercms/commons/http/CookieManager.java
utilities/src/main/java/org/craftercms/commons/http/RequestContextBindingFilter.java
utilities/src/main/java/org/craftercms/commons/i10n/I10nLogger.java
utilities/src/main/java/org/craftercms/commons/i10n/I10nUtils.java
utilities/src/main/java/org/craftercms/commons/logging/I10nMethodLogger.java
utilities/src/main/java/org/craftercms/commons/mail/EmailException.java
utilities/src/main/java/org/craftercms/commons/mail/impl/EmailFactoryImpl.java
utilities/src/main/java/org/craftercms/commons/mail/impl/EmailImpl.java
utilities/src/main/java/org/craftercms/commons/rest/HttpMessageConvertingResponseWriter.java
validation/src/main/java/org/craftercms/commons/validation/ErrorCodes.java
validation/src/main/java/org/craftercms/commons/validation/ValidationResult.java
validation/src/main/java/org/craftercms/commons/validation/ValidationUtils.java
validation/src/main/java/org/craftercms/commons/validation/rest/ValidationAwareRestExceptionHandlers.java
validation/src/main/java/org/craftercms/commons/validation/validators/Validator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/AbstractNumberValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/BasicValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/SecurePathValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/StringValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/ValidateParamsAspect.java

* Removed property that was already inherited.

Small code fix:

---

validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateNoTagsParam.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/AnnotationBasedValidatorFactoryRegistry.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/NoTagsParamValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/NoTagsValidator.java

* Added @ValidateNoTagsParam to enable validation of text that shouldn't have HTML/XML tags.

Added validation annotation:

---

validation/src/main/java/org/craftercms/commons/validation/validators/impl/NoTagsValidator.java

* Added &lt; and &gt; regex validation.

Validation enhancements

---

validation/pom.xml
validation/src/main/java/org/craftercms/commons/validation/validators/Validator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/SecurePathValidator.java
validation/src/test/java/org/craftercms/commons/validation/validators/impl/SecurePathValidatorTest.java

* Fixed issue with false positive in SecurePathValidator (issue craftercms/craftercms#1584).
* Added unit test for SecurityPathValidator.

Validation fixes:

---

utilities/src/main/java/org/craftercms/commons/converters/Converter.java
utilities/src/main/java/org/craftercms/commons/converters/impl/StringToBooleanConverter.java
utilities/src/main/java/org/craftercms/commons/converters/impl/StringToDateConverter.java
utilities/src/main/java/org/craftercms/commons/converters/impl/StringToDoubleConverter.java
utilities/src/main/java/org/craftercms/commons/converters/impl/StringToFloatConverter.java
utilities/src/main/java/org/craftercms/commons/converters/impl/StringToIntegerConverter.java
utilities/src/main/java/org/craftercms/commons/converters/impl/StringToLongConverter.java
utilities/src/main/java/org/craftercms/commons/converters/impl/StringToShortConverter.java

* Added Converter.getSourceClass and Converter.getTargetClass().

Fix for 1826:

---

utilities/src/main/java/org/craftercms/commons/converters/impl/StringToStringConverter.java
utilities/src/main/java/org/craftercms/commons/http/RequestContext.java

* StringToStringConverter added.

Solves #1842:

---

pom.xml

Ticket craftercms/craftercms#2305

Removed swagger version property

---

pom.xml

https://github.com/craftercms/craftercms/issues/2322

Updated logback version

---

security/src/main/java/org/craftercms/commons/security/exception/ActionDeniedException.java
security/src/main/java/org/craftercms/commons/security/permissions/Permission.java
security/src/main/java/org/craftercms/commons/security/permissions/PermissionEvaluator.java
security/src/main/java/org/craftercms/commons/security/permissions/PermissionResolver.java
security/src/main/java/org/craftercms/commons/security/permissions/ProtectedResourceBase.java
security/src/main/java/org/craftercms/commons/security/permissions/annotations/HasPermissionAnnotationHandler.java
security/src/main/java/org/craftercms/commons/security/permissions/annotations/ProtectedResource.java
security/src/main/java/org/craftercms/commons/security/permissions/annotations/ProtectedResourceId.java
security/src/main/java/org/craftercms/commons/security/permissions/impl/PermissionEvaluatorImpl.java
security/src/main/resources/crafter/security/messages/logging.properties
security/src/test/java/org/craftercms/commons/security/permissions/HasPermissionAnnotationHandlerTest.java

* Changed the name of SecuredObject to ProtectedResource.
* Several resource IDs can now be specified when annotating a method for permissioning (with ProtectedResourceId annotation).
Ticket craftercms/craftercms#2577

Enhancements for permissioning:

---

mongo/pom.xml
pom.xml

Ticket craftercms/craftercms#2589

Upgrade Jackson version to 2.9.7

---

mongo/pom.xml
pom.xml

Ticket craftercms/craftercms#2589

Upgraded Jackson to 2.9.7

---

utilities/src/main/java/org/craftercms/commons/file/RemoteFileStore.java
utilities/src/main/java/org/craftercms/commons/file/impl/AbstractRemoteFileStore.java
utilities/src/main/java/org/craftercms/commons/file/impl/RegexMappedCompositeFileStore.java
utilities/src/main/java/org/craftercms/commons/file/impl/UrlBasedFileStore.java

Ticket craftercms/craftercms#2624

Added RemoteFileStore implementations.

---

utilities/src/main/java/org/craftercms/commons/jackson/search/CrafterMultivaluedModule.java
utilities/src/main/java/org/craftercms/commons/jackson/search/MixedMultivaluedMap.java

https://github.com/craftercms/craftercms/issues/2253

Add new utility classes for jackson

---

utilities/src/main/java/org/craftercms/commons/config/ConfigUtils.java
utilities/src/main/java/org/craftercms/commons/config/MissingConfigurationException.java
utilities/src/main/java/org/craftercms/commons/config/profiles/AbstractProfileConfigMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3ProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/box/BoxProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/webdav/WebDavProfileMappper.java
utilities/src/main/java/org/craftercms/commons/file/stores/impl/AbstractProfileAwareRemoteFileStore.java

Ticket craftercms/craftercms#2592

Added common configuration methods and classes.

---

entitlements/src/main/java/org/craftercms/commons/entitlements/validator/EntitlementValidator.java

https://github.com/craftersoftware/license-manager/issues/39, https://github.com/craftersoftware/license-manager/issues/40

Add new method for entitlement validator

---

utilities/src/main/java/org/craftercms/commons/config/profiles/box/BoxProfileMapper.java
utilities/src/main/java/org/craftercms/commons/file/stores/impl/box/BoxFileStore.java

Ticket craftercms/craftercms#2578

Quick fix for Box indexing.

---

pom.xml

Ticket craftercms/craftercms#2673

Upgrade Jackson to 2.9.8

---

entitlements/src/main/java/org/craftercms/commons/entitlements/exception/EntitlementExceededException.java
entitlements/src/main/java/org/craftercms/commons/entitlements/exception/EntitlementException.java
entitlements/src/main/java/org/craftercms/commons/entitlements/exception/UnsupportedEntitlementException.java
entitlements/src/main/java/org/craftercms/commons/entitlements/model/Entitlement.java
entitlements/src/main/java/org/craftercms/commons/entitlements/model/EntitlementType.java
entitlements/src/main/java/org/craftercms/commons/entitlements/model/Module.java
entitlements/src/main/java/org/craftercms/commons/entitlements/usage/EntitlementUsageProvider.java
entitlements/src/main/java/org/craftercms/commons/entitlements/validator/DbIntegrityValidator.java
entitlements/src/main/java/org/craftercms/commons/entitlements/validator/EntitlementValidator.java
entitlements/src/main/java/org/craftercms/commons/entitlements/validator/impl/DefaultDbIntegrityValidatorImpl.java
entitlements/src/main/java/org/craftercms/commons/entitlements/validator/impl/DefaultEntitlementValidatorImpl.java

Copyright updated

---

utilities/src/main/java/org/craftercms/commons/file/stores/RemoteFile.java
utilities/src/main/java/org/craftercms/commons/file/stores/impl/ResourceBasedRemoteFile.java

https://github.com/craftercms/craftercms/issues/2723

Add content length support for remote files

---

utilities/src/main/java/org/craftercms/commons/web/CORSFilter.java

- Add support for preflight request
- Validate the values of the header against the configuration
https://github.com/craftercms/craftercms/issues/2919

Update CORS filter:

---

utilities/src/main/java/org/craftercms/commons/web/CORSFilter.java

- Add support for preflight request
- Validate the values of the header against the configuration
https://github.com/craftercms/craftercms/issues/2919

 Update CORS filter:

---

utilities/src/main/java/org/craftercms/commons/cache/EhCacheFactoryBean.java

Added destroy method to EhCacheFactoryBean to avoid hanging threads on shutdown.
Ticket craftercms/craftercms#2939

Added destroy method to EhCacheFactoryBean

---

utilities/src/main/java/org/craftercms/commons/web/AddResponseHeaderFilter.java

https://github.com/craftercms/craftercms/issues/2668

Add new filter to utilities

---

pom.xml

Ticket craftercms/craftercms#3011

Upgrade Box version

---

utilities/src/main/java/org/craftercms/commons/spring/ListMergingPostProcessor.java

Added ListMergingPostProcessor, useful for merging lists before beans are instantiated
Ticket craftercms/craftercms#3049

Added ListMergingPostProcessor

---

pom.xml

Ticket craftercms/craftercms#3150

Upgraded Jackson version.

---

utilities/src/main/java/org/craftercms/commons/config/ConfigurationMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3ProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/box/BoxProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/webdav/WebDavProfileMappper.java

https://github.com/craftercms/craftercms/issues/2736

Fix for javadoc warnings

---

mongo/src/main/java/org/craftercms/commons/mongo/AbstractJongoRepository.java
mongo/src/main/java/org/craftercms/commons/mongo/CrudRepository.java
mongo/src/main/java/org/craftercms/commons/mongo/JongoFactoryBean.java
mongo/src/main/java/org/craftercms/commons/mongo/MongoScriptRunner.java
utilities/src/main/java/org/craftercms/commons/jackson/mvc/CrafterJacksonAnnotationIntrospector.java

https://github.com/craftercms/craftercms/issues/2736

Fix deprecated & unchecked warnings

---

utilities/src/main/java/org/craftercms/commons/config/profiles/AbstractProfileConfigMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3ProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/box/BoxProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/webdav/WebDavProfileMappper.java

https://github.com/craftercms/craftercms/issues/3232

Updates for new configuration file structure

---

utilities/src/main/java/org/craftercms/commons/collections/MapUtils.java
utilities/src/main/java/org/craftercms/commons/rest/RestTemplate.java

Enhancements needed to support serverless delivery target creation in Studio
Ticker craftercms/craftercms#3282

Serverless delivery enhancements

---

entitlements/pom.xml
mongo/pom.xml
pom.xml
utilities/pom.xml
validation/pom.xml

https://github.com/craftercms/craftercms/issues/3315

Upgrade Jackson Databind version

---

entitlements/src/main/java/org/craftercms/commons/entitlements/validator/impl/DefaultDbIntegrityValidatorImpl.java

Fix upgrade DB integrity issues
https://github.com/craftercms/craftercms/issues/3320

CRAFTERCMS-3320

---

plugin/pom.xml
plugin/src/main/java/org/craftercms/commons/plugin/model/Version.java

https://github.com/craftercms/craftercms/issues/3343

Updates for plugins model

---

pom.xml
utilities/pom.xml
utilities/src/main/java/org/craftercms/commons/config/profiles/webdav/WebDavProfile.java
utilities/src/main/java/org/craftercms/commons/file/stores/WebDavUtils.java
utilities/src/main/java/org/craftercms/commons/file/stores/impl/webdav/WebDavFileStore.java
utilities/src/main/java/org/craftercms/commons/spring/resources/WebDavResource.java

https://github.com/craftercms/craftercms/issues/3420

Add WebDAV support for remote files

---

pom.xml
utilities/pom.xml

Upgraded:
- Commons Bean Utils
- Jackson

Upgraded dependencies

---

plugin/src/main/java/org/craftercms/commons/plugin/impl/PluginDescriptorReaderImpl.java
plugin/src/main/java/org/craftercms/commons/plugin/model/Parameter.java
plugin/src/main/java/org/craftercms/commons/plugin/model/Plugin.java
plugin/src/test/java/org/craftercms/commons/plugin/PluginDescriptorReaderImplTest.java
plugin/src/test/resources/plugin/craftercms-plugin-params.yaml

- Add support for parameters in the plugin descriptor
https://github.com/craftercms/craftercms/issues/3002

Updates for plugins:

---

plugin/src/main/java/org/craftercms/commons/plugin/model/Version.java

Make version optional for plugin search

---

plugin/src/main/java/org/craftercms/commons/plugin/model/Parameter.java

https://github.com/craftercms/craftercms/issues/3486

Add new fields for plugin parameters

---

entitlements/src/main/java/org/craftercms/commons/entitlements/validator/impl/DefaultDbIntegrityValidatorImpl.java

Implemented configurable DB schema feature
https://github.com/craftercms/craftercms/issues/3503

CRAFTERCMS-3503

---

utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfile.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3Profile.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3ProfileMapper.java
utilities/src/main/java/org/craftercms/commons/file/stores/S3Utils.java

- Support for custom endpoints for all AWS profiles
https://github.com/craftercms/craftercms/issues/3550

Improve AWS related classes:

---

utilities/src/main/java/org/craftercms/commons/exceptions/InvalidManagementTokenException.java
utilities/src/main/java/org/craftercms/commons/exceptions/InvalidMonitoringTokenException.java
utilities/src/main/java/org/craftercms/commons/monitoring/rest/MonitoringRestControllerBase.java

Added authorization token for monitoring APIs
https://github.com/craftercms/craftercms/issues/3577

[3577] [studio] /studio/api/2/monitoring API enhancement

---

utilities/pom.xml
utilities/src/main/java/org/craftercms/commons/config/ConfigUtils.java
utilities/src/main/java/org/craftercms/commons/config/EncryptionAwareConfigurationReader.java
utilities/src/main/java/org/craftercms/commons/config/MultiResourceConfigurationBuilder.java
utilities/src/main/java/org/craftercms/commons/config/profiles/AbstractProfileConfigMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3ProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/box/BoxProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/webdav/WebDavProfileMapper.java

https://github.com/craftersoftware/craftercms/issues/18

Refactor to support encrypted properties in all modules

---

utilities/src/main/java/org/craftercms/commons/concurrent/locks/AbstractWeakKeyBasedLockFactory.java
utilities/src/main/java/org/craftercms/commons/concurrent/locks/KeyBasedLockFactory.java
utilities/src/main/java/org/craftercms/commons/concurrent/locks/WeakKeyBasedReentrantLockFactory.java

Added key based locking factory

---

utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3Profile.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3ProfileMapper.java
utilities/src/main/java/org/craftercms/commons/file/stores/S3Utils.java

https://github.com/craftercms/craftercms/issues/3751

Add support for path style access in S3 profiles

---

utilities/src/main/java/org/craftercms/commons/aws/AbstractAwsClientCachingFactory.java

Added missing copyright

---

entitlements/src/main/java/org/craftercms/commons/entitlements/validator/impl/DefaultDbIntegrityValidatorImpl.java

Fix problem with integrity query after db upgrade
https://github.com/craftercms/craftercms/issues/3734

[3734] [craftercms] Fail to upgrade authoring from 3.0.26 to 3.1.4

---

pom.xml
upgrade-manager/pom.xml
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/UpgradeManager.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/UpgradeOperation.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/UpgradePipeline.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/UpgradePipelineFactory.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/VersionProvider.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/exception/UpgradeException.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/AbstractUpgradeManager.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/operations/AbstractUpgradeOperation.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/operations/UpdateVersionUpgradeOperation.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineFactoryImpl.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineImpl.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/providers/AbstractFileVersionProvider.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/providers/AbstractVersionProvider.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/providers/YamlFileVersionProvider.java
upgrade-manager/src/test/java/org/craftercms/commons/upgrade/impl/operations/UpdateVersionUpgradeOperationTest.java
upgrade-manager/src/test/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineImplTest.java

- Generic version of the upgrade manager to be used by other projects
https://github.com/craftercms/craftercms/issues/3792

Add new module:

---

utilities/src/main/java/org/craftercms/commons/config/ConfigurationMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/AbstractProfileConfigMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3Profile.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3ProfileMapper.java

https://github.com/craftercms/craftercms/issues/3744

Updates for Studio Blob Storage

---

utilities/src/main/java/org/craftercms/commons/file/blob/Blob.java
utilities/src/main/java/org/craftercms/commons/file/blob/BlobStore.java
utilities/src/main/java/org/craftercms/commons/file/blob/BlobStoreResolver.java
utilities/src/main/java/org/craftercms/commons/file/blob/BlobUrlResolver.java
utilities/src/main/java/org/craftercms/commons/file/blob/EnvironmentResolver.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/AbstractBlobStore.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/BlobStoreResolverImpl.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/BlobUrlResolverImpl.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/FixedEnvironmentResolver.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/s3/AwsS3BlobStore.java
utilities/src/main/java/org/craftercms/commons/spring/resources/S3Resource.java
utilities/src/test/java/org/craftercms/commons/file/blob/impl/AbstractBlobStoreTest.java
utilities/src/test/resources/config/stores.xml

- Add new classes shared by other modules
https://github.com/craftercms/craftercms/issues/3744

New classes for Blob Store:

---

utilities/src/main/java/org/craftercms/commons/file/blob/impl/s3/AwsS3BlobStore.java

https://github.com/craftercms/craftercms/issues/3744

Fix for blob files

---

utilities/src/main/java/org/craftercms/commons/file/blob/impl/s3/AwsS3BlobStore.java

Fix parameter order

---

utilities/src/main/java/org/craftercms/commons/file/blob/Blob.java

https://github.com/craftercms/craftercms/issues/3744

Fix for blob file updates

---

utilities/src/main/java/org/craftercms/commons/aws/AbstractAwsClientCachingFactory.java

Ticket craftercms/craftercms#3877

Fixed dispose/destroy of AWS client factory

---

utilities/src/main/java/org/craftercms/commons/file/blob/Blob.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/AbstractBlobStore.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/s3/AwsS3BlobStore.java

Remove siteId reference from blob files

---

utilities/src/main/java/org/craftercms/commons/file/blob/impl/AbstractBlobStore.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/s3/AwsS3BlobStore.java
utilities/src/test/java/org/craftercms/commons/file/blob/impl/s3/AwsS3BlobStoreTest.java

Fix for S3 keys

---

pom.xml
utilities/pom.xml

https://github.com/craftercms/craftercms/issues/3874

Update jackson version

---

utilities/src/main/java/org/craftercms/commons/file/blob/BlobStore.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/AbstractBlobStore.java
utilities/src/test/resources/config/stores.xml

- Remove references to `environment` in the configuration
https://github.com/craftercms/craftercms/issues/3914

Update for blob stores:

---

utilities/src/main/java/org/craftercms/commons/config/ConfigurationMapper.java
utilities/src/main/java/org/craftercms/commons/config/ConfigurationProvider.java
utilities/src/main/java/org/craftercms/commons/config/ConfigurationResolver.java
utilities/src/main/java/org/craftercms/commons/config/ConfigurationResolverImpl.java
utilities/src/main/java/org/craftercms/commons/config/EncryptionAwareConfigurationReader.java
utilities/src/main/java/org/craftercms/commons/config/profiles/AbstractProfileConfigMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3ProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/box/BoxProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/webdav/WebDavProfileMapper.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/BlobStoreResolverImpl.java

https://github.com/craftercms/craftercms/issues/3960

Add support for multi-environment configurations

---

pom.xml
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineFactoryImpl.java
utilities/pom.xml

https://github.com/craftercms/craftercms/issues/3831

Fix build warnings

---

upgrade-manager/src/main/java/org/craftercms/commons/upgrade/UpgradeManager.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/UpgradeOperation.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/UpgradePipeline.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/UpgradePipelineFactory.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/AbstractUpgradeManager.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/operations/AbstractUpgradeOperation.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/operations/UpdateVersionUpgradeOperation.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineFactoryImpl.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineImpl.java
upgrade-manager/src/test/java/org/craftercms/commons/upgrade/impl/operations/AbstractUpgradeOperationTest.java
upgrade-manager/src/test/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineImplTest.java

- Most classes use generics now for cleaner code
- Fix some format issues
https://github.com/craftercms/craftercms/issues/4068

Improvements for Upgrade Manager:

---

utilities/src/main/java/org/craftercms/commons/locale/LocaleUtils.java

https://github.com/craftercms/craftercms/issues/4021

Add locale utility class

---

utilities/src/main/java/org/craftercms/commons/file/blob/impl/BlobStoreResolverImpl.java

https://github.com/craftercms/craftercms/issues/4169

Refactor to support caching blob stores

---

utilities/src/main/java/org/craftercms/commons/jackson/mvc/CrafterJackson2MessageConverter.java

https://github.com/craftercms/craftercms/issues/4107

Fix for custom Jackson message converter

---

utilities/src/main/java/org/craftercms/commons/locale/LocaleUtils.java

https://github.com/craftercms/craftercms/issues/4021

Improvements for locale support

---

utilities/src/main/java/org/craftercms/commons/crypto/impl/AesTextEncryptor.java
utilities/src/main/java/org/craftercms/commons/crypto/impl/PbkAesTextEncryptor.java

https://github.com/craftercms/craftercms/issues/4178

Fix for encryption/decryption

---

utilities/src/main/java/org/craftercms/commons/locale/LocaleUtils.java

https://github.com/craftercms/craftercms/issues/4021

Improvements for locale codes

---

utilities/src/main/java/org/craftercms/commons/crypto/impl/PbkAesTextEncryptor.java

https://github.com/craftercms/craftercms/issues/4178

Update according to feedback

---

utilities/src/main/java/org/craftercms/commons/web/CloudfrontForwardedHeaderFilter.java
utilities/src/main/java/org/craftercms/commons/web/ForwardedHeaderFilter.java

https://github.com/craftercms/craftercms/issues/4205

Add new web filter for Cloudfront

---

utilities/src/main/java/org/craftercms/commons/web/ForwardedHeaderFilter.java

Fix build error

---

audit/pom.xml
ebus/pom.xml
entitlements/pom.xml
git/pom.xml
mongo/pom.xml
plugin/pom.xml
pom.xml
security/pom.xml
upgrade-manager/pom.xml
utilities/pom.xml
utilities/src/main/java/org/craftercms/commons/crypto/impl/PbkAesTextEncryptor.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/BlobStoreResolverImpl.java
utilities/src/main/java/org/craftercms/commons/jackson/mvc/CrafterJackson2MessageConverter.java
utilities/src/main/java/org/craftercms/commons/web/CloudfrontForwardedHeaderFilter.java
utilities/src/main/java/org/craftercms/commons/web/ForwardedHeaderFilter.java
validation/pom.xml

Sync with support/3.1.x

---

upgrade-manager/src/main/java/org/craftercms/commons/upgrade/UpgradeOperation.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/UpgradePipelineFactory.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/VersionProvider.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/AbstractUpgradeManager.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/UpgradeContext.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/operations/AbstractUpgradeOperation.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/operations/UpdateVersionUpgradeOperation.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineFactoryImpl.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineImpl.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/providers/AbstractFileVersionProvider.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/providers/AbstractVersionProvider.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/providers/YamlFileVersionProvider.java
upgrade-manager/src/test/java/org/craftercms/commons/upgrade/impl/operations/AbstractUpgradeOperationTest.java
upgrade-manager/src/test/java/org/craftercms/commons/upgrade/impl/operations/UpdateVersionUpgradeOperationTest.java

- Small changes needed to use these classes in Studio
https://github.com/craftercms/craftercms/issues/3801

Refactor for Upgrade Manager:

---

pom.xml

https://github.com/craftercms/craftercms/issues/4259

3.1.x/feature/4259

---

upgrade-manager/pom.xml
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/UpgradePipelineFactory.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/exception/UpgradeNotSupportedException.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineFactoryImpl.java
upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineImpl.java
upgrade-manager/src/test/java/org/craftercms/commons/upgrade/impl/pipeline/DefaultUpgradePipelineFactoryImplTest.java
upgrade-manager/src/test/resources/pipeline-factory-test.yaml

- Fix versions being updated only at the end of the pipelines
- Add optional version requirements for pipelines
https://github.com/craftercms/craftercms/issues/4264, https://github.com/craftercms/craftercms/issues/4272
Depends on https://github.com/craftercms/craftercms/pull/4309

Upgrade Manager:

---

plugin/src/main/java/org/craftercms/commons/plugin/model/Version.java

https://github.com/craftercms/craftercms/issues/4327

Fix regex to detect versions

---

utilities/src/main/java/org/craftercms/commons/config/profiles/webdav/WebDavProfile.java
utilities/src/main/java/org/craftercms/commons/config/profiles/webdav/WebDavProfileMapper.java
utilities/src/main/java/org/craftercms/commons/file/stores/WebDavUtils.java
utilities/src/main/java/org/craftercms/commons/file/stores/impl/webdav/WebDavFileStore.java

- Add optional support for preemptive authentication
https://github.com/craftercms/craftercms/issues/4374

Fix for webdav:

---

utilities/src/main/java/org/craftercms/commons/file/blob/BlobStoreException.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/s3/AwsS3BlobStore.java

https://github.com/craftercms/craftercms/issues/4452

Improve blob store exception handling

---

utilities/pom.xml
utilities/src/main/java/org/craftercms/commons/spring/context/ApplicationContextAccessor.java
utilities/src/main/java/org/craftercms/commons/spring/context/RestrictedApplicationContext.java
utilities/src/main/java/org/craftercms/commons/spring/groovy/SandboxInterceptorFactory.java

- Move common classes used by Engine, Studio & Deployer
https://github.com/craftercms/craftercms/issues/4390

Refactor for scripting:

---

upgrade-manager/src/main/java/org/craftercms/commons/upgrade/impl/providers/YamlFileVersionProvider.java
utilities/src/main/java/org/craftercms/commons/config/DisableClassLoadingConstructor.java
utilities/src/main/java/org/craftercms/commons/config/YamlConfiguration.java

https://github.com/craftersoftware/craftercms/issues/220

Disable class loading for YAML

---

utilities/src/main/java/org/craftercms/commons/jackson/CustomSerializationObjectMapper.java

https://github.com/craftercms/craftercms/issues/4429

Fix to properly register Jackson modules

---

git/src/main/java/org/craftercms/commons/git/utils/GitUtils.java

https://github.com/craftercms/craftercms/issues/4510

Refactor for common git related code

---

utilities/src/main/java/org/craftercms/commons/file/blob/impl/BlobStoreResolverImpl.java

https://github.com/craftercms/craftercms/issues/4002

Improve logging for blob stores

---

utilities/src/main/java/org/craftercms/commons/file/blob/BlobStoreResolver.java
utilities/src/main/java/org/craftercms/commons/file/blob/exception/BlobStoreConfigurationMissingException.java
utilities/src/main/java/org/craftercms/commons/file/blob/exception/BlobStoreException.java
utilities/src/main/java/org/craftercms/commons/file/blob/exception/BlobStoreMissingException.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/BlobStoreResolverImpl.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/s3/AwsS3BlobStore.java

https://github.com/craftercms/craftercms/issues/4002

Improvements for blob store exception handling

---

utilities/src/main/java/org/craftercms/commons/converters/impl/StringToDateConverter.java

https://github.com/craftercms/craftercms/issues/4592

Fix for empty date fields

---

pom.xml

Ticket https://github.com/craftercms/craftercms/issues/4630

Upgraded AWS SDK to latest 1.11.x

---

plugin/src/main/java/org/craftercms/commons/plugin/model/Installation.java
plugin/src/main/java/org/craftercms/commons/plugin/model/Plugin.java

https://github.com/craftercms/craftercms/issues/4627

Improvements for plugin installation

---

utilities/src/main/java/org/craftercms/commons/config/ConfigurationResolverImpl.java
utilities/src/main/java/org/craftercms/commons/config/FixedPublishingTargetResolver.java
utilities/src/main/java/org/craftercms/commons/config/profiles/webdav/WebDavProfileMapper.java
utilities/src/main/java/org/craftercms/commons/crypto/impl/PbkAesTextEncryptor.java
utilities/src/main/java/org/craftercms/commons/spring/cors/FixedCorsConfigurationSource.java
utilities/src/main/java/org/craftercms/commons/spring/groovy/SandboxInterceptorFactory.java
utilities/src/main/java/org/craftercms/commons/web/CloudfrontForwardedHeaderFilter.java
utilities/src/main/java/org/craftercms/commons/web/ForwardedHeaderFilter.java

Updates for named parameters in Spring

---

utilities/src/main/java/org/craftercms/commons/spring/groovy/SandboxInterceptorFactory.java

craftersoftware/craftercms#240
Depends on craftercms/script-security-plugin#14

Updates for new sandbox restrictions

---

utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfile.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3Profile.java

Fixed AWS Profile to do a more correct generation of equals and hascode (needed for S3 client chaching)

---

utilities/src/main/java/org/craftercms/commons/converters/impl/StringToDoubleConverter.java
utilities/src/main/java/org/craftercms/commons/converters/impl/StringToFloatConverter.java
utilities/src/main/java/org/craftercms/commons/converters/impl/StringToIntegerConverter.java
utilities/src/main/java/org/craftercms/commons/converters/impl/StringToLongConverter.java
utilities/src/main/java/org/craftercms/commons/converters/impl/StringToShortConverter.java

https://github.com/craftercms/craftercms/issues/4811

Fix for number converters

---

utilities/src/main/java/org/craftercms/commons/config/EncryptionAwareConfigurationReader.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3ProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/box/BoxProfileMapper.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/BlobUrlResolverImpl.java
utilities/src/main/java/org/craftercms/commons/rest/HttpMessageConvertingResponseWriter.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/SecurePathValidator.java

https://github.com/craftercms/craftercms/issues/4708

Update constructor-args to be named

---

utilities/src/main/java/org/craftercms/commons/file/blob/impl/BlobStoreResolverImpl.java

https://github.com/craftercms/craftercms/issues/4702

Improve errors for blob store

---

utilities/src/main/java/org/craftercms/commons/config/ConfigUtils.java
utilities/src/main/java/org/craftercms/commons/config/EncryptionAwareConfigurationReader.java
utilities/src/test/java/org/craftercms/commons/file/blob/impl/AbstractBlobStoreTest.java

https://github.com/craftercms/craftercms/issues/4354

Fix for lists in xml config files

---

plugin/src/main/java/org/craftercms/commons/plugin/model/Plugin.java

https://github.com/craftercms/craftercms/issues/4944

Add new field for plugins

---

plugin/src/main/java/org/craftercms/commons/plugin/model/SearchEngines.java

https://github.com/craftercms/craftercms/issues/4772

Mark crafter-search as deprecated

---

utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfile.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfileMapper.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3Profile.java

https://github.com/craftersoftware/craftercms/issues/254

Fix for AWS S3 client caching

---

plugin/src/main/java/org/craftercms/commons/plugin/model/Installation.java
plugin/src/main/java/org/craftercms/commons/plugin/model/Parameter.java

https://github.com/craftercms/craftercms/issues/5086

Updates for plugin classes

---

git/src/main/java/org/craftercms/commons/git/auth/AbstractSshAuthConfigurator.java
git/src/main/java/org/craftercms/commons/git/auth/SshRsaKeyPairAuthConfigurator.java
git/src/main/java/org/craftercms/commons/git/auth/SshUsernamePasswordAuthConfigurator.java

Upgrade JGit to 6
https://github.com/craftercms/craftercms/issues/5213

[5213] [all] Upgrade to JGit 6

---

audit/pom.xml
ebus/pom.xml
entitlements/pom.xml
git/pom.xml
mongo/pom.xml
plugin/pom.xml
pom.xml
security/pom.xml
upgrade-manager/pom.xml
utilities/pom.xml
validation/pom.xml

Sync with 3.1.x

---

utilities/src/main/java/org/craftercms/commons/monitoring/StatusInfo.java

Remove final to allow class to be extended in studio
https://github.com/craftersoftware/craftercms/issues/258

[258E] [studio] Implement a Primary/Replica clustering approach for Crafter CMS v4

---

utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3Profile.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/S3ProfileMapper.java
utilities/src/main/java/org/craftercms/commons/spring/resources/S3Resource.java

https://github.com/craftercms/craftercms/issues/5377

Add optional prefix for AWS S3 profiles

---

utilities/src/main/java/org/craftercms/commons/spring/cors/FixedCorsConfigurationSource.java

https://github.com/craftercms/craftercms/issues/5381

Support patterns in CORS config

---

utilities/src/main/java/org/craftercms/commons/spring/cors/FixedCorsConfigurationSource.java

https://github.com/craftercms/craftercms/issues/5381

Fix for patterns in CORS config

---

security/pom.xml
security/src/main/java/org/craftercms/commons/security/permissions/annotations/HasPermission.java
security/src/main/java/org/craftercms/commons/security/permissions/annotations/HasPermissionAnnotationHandler.java
security/src/test/java/org/craftercms/commons/security/permissions/HasPermissionAnnotationHandlerTest.java

https://github.com/craftersoftware/craftercms/issues/350
Adding support for management tokens to HasPermission annotation

Adding support for management tokens to HasPermission annotation

---

validation/pom.xml
validation/src/main/java/org/craftercms/commons/validation/ErrorCodes.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/EsapiValidatedParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/EsapiValidationType.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/AnnotationBasedValidatorFactoryRegistry.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/EsapiValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/EsapiValidatorFactory.java
validation/src/main/resources/crafter/commons/validation/errors.properties
validation/src/main/resources/esapi/ESAPI.properties
validation/src/main/resources/esapi/validation.properties

https://github.com/craftersoftware/craftercms/issues/464

Adding param validator

---

validation/src/main/java/org/craftercms/commons/validation/annotations/param/EsapiValidationType.java

https://github.com/craftersoftware/craftercms/issues/465
Parameter name esapi validation type

Parameter name esapi validation type

---

pom.xml
utilities/src/main/java/org/craftercms/commons/monitoring/rest/MonitoringRestControllerBase.java
utilities/src/main/java/org/craftercms/commons/rest/ManagementTokenAware.java
validation/pom.xml
validation/src/main/java/org/craftercms/commons/validation/ErrorCodes.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/EsapiValidatedParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/EsapiValidationType.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/AnnotationBasedValidatorFactoryRegistry.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/EsapiValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/EsapiValidatorFactory.java
validation/src/main/resources/crafter/commons/validation/errors.properties
validation/src/main/resources/esapi/ESAPI.properties
validation/src/main/resources/esapi/validation.properties

https://github.com/craftersoftware/craftercms/issues/464

Port changes back to 3.1.x

---

validation/src/main/java/org/craftercms/commons/validation/annotations/param/EsapiValidationType.java

https://github.com/craftersoftware/craftercms/issues/465
Parameter name validation type

Parameter name validation type

---

validation/src/main/java/org/craftercms/commons/validation/ErrorCodes.java
validation/src/main/java/org/craftercms/commons/validation/ValidationUtils.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateCollectionParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateDoubleParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateIntegerParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateLongParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateNoTagsParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateObjectParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateSecurePathParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateStringParam.java
validation/src/main/java/org/craftercms/commons/validation/validators/AnnotationBasedValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/Validator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/AbstractNumberValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/AnnotationBasedValidatorFactoryRegistry.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/CollectionParamValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/CollectionValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/DoubleParamValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/EsapiValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/EsapiValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/IntegerParamValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/LongParamValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/NoTagsParamValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/ObjectParamValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/ObjectParamValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/SecurePathParamValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/StringParamValidatorFactory.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/StringValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/ValidateParamsAspect.java
validation/src/main/resources/crafter/commons/validation/errors.properties
validation/src/main/resources/esapi/ESAPI.properties

https://github.com/craftersoftware/craftercms/issues/470

Adding support for Collection parameter validation

---

validation/src/main/resources/esapi/ESAPI.properties

Prevent comma in SQL_ORDER_BY param

Prevent comma in SQL_ORDER_BY param

---

validation/src/main/java/org/craftercms/commons/validation/annotations/param/EsapiValidationType.java
validation/src/main/resources/crafter/commons/validation/errors.properties
validation/src/main/resources/esapi/ESAPI.properties

https://github.com/craftersoftware/craftercms/issues/410

Add keyword pattern for esapi

---

utilities/src/main/java/org/craftercms/commons/proxy/ProxyUtils.java

https://github.com/craftersoftware/craftercms/issues/478

Add ProxyUtils

---

validation/src/main/resources/esapi/ESAPI.properties

https://github.com/craftercms/craftercms/issues/6002

Update asset path write regex

---

mongo/pom.xml
mongo/src/main/java/org/craftercms/commons/mongo/AbstractJongoRepository.java
mongo/src/main/java/org/craftercms/commons/mongo/FileInfo.java
mongo/src/main/java/org/craftercms/commons/mongo/JongoFactoryBean.java
mongo/src/main/java/org/craftercms/commons/mongo/MongoClientOptionsFactory.java
mongo/src/main/java/org/craftercms/commons/mongo/MongoScriptRunner.java

Upgrade MongoDB to 6.0.5

---

utilities/src/main/java/org/craftercms/commons/monitoring/rest/MonitoringRestControllerBase.java

https://github.com/craftercms/craftercms/issues/6020
https://github.com/craftercms/craftercms/issues/6021

Engine should support health check per context

---

utilities/src/main/java/org/craftercms/commons/spring/ConditionalFactoryBean.java

https://github.com/craftercms/craftercms/issues/6208

Use constructor for ConditionalFactoryBean

---

security/src/main/java/org/craftercms/commons/security/permissions/annotations/AbstractPermissionAnnotationHandler.java
security/src/main/java/org/craftercms/commons/security/permissions/annotations/HasPermissionAnnotationHandler.java
security/src/test/java/org/craftercms/commons/security/permissions/HasPermissionAnnotationHandlerTest.java
utilities/src/main/java/org/craftercms/commons/file/blob/BlobStore.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/BlobStoreResolverImpl.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/s3/AwsS3BlobStore.java

https://github.com/craftercms/craftercms/issues/6199
Support for elements meta-annotated with ProtectedResourceId
Tweaks to support read-only BlobStores

Duplicate Project/Site

---

ebus/pom.xml

https://github.com/craftersoftware/craftercms/issues/606
Dependencies update

Dependencies update

---

utilities/src/main/java/org/craftercms/commons/config/ConfigUtils.java
utilities/src/main/java/org/craftercms/commons/config/EncryptionAwareConfigurationReader.java
utilities/src/main/java/org/craftercms/commons/config/YamlConfiguration.java

https://github.com/craftersoftware/craftercms/issues/616
Disable aliases for collections in yaml

Disable aliases for collections in yaml

---

.travis.yml
utilities/src/test/java/org/craftercms/commons/config/YamlConfigurationTest.java

https://github.com/craftersoftware/craftercms/issues/621

Update Travis CI install and script

---

validation/src/main/resources/esapi/ESAPI.properties
validation/src/test/java/org/craftercms/commons/validation/validators/impl/ContentPathReadValidatorTest.java

https://github.com/craftersoftware/craftercms/issues/627

Update CONTENT_PATH_READ to allow at most 2 consecutive forward slash character

---

mongo/src/test/java/org/craftercms/commons/mongo/UpdateHelperTest.java
utilities/src/test/java/org/craftercms/commons/file/blob/impl/AbstractBlobStoreTest.java

https://github.com/craftercms/craftercms/issues/6278

Update test cases

---

utilities/src/main/java/org/craftercms/commons/proxy/ProxyUtils.java

https://github.com/craftercms/craftercms/issues/6511

Check if no cookie is sent while proxying

---

utilities/pom.xml

https://github.com/craftercms/craftercms/issues/5977

update jakarta.activation dependencies

---

plugin/pom.xml
plugin/src/main/java/org/craftercms/commons/plugin/model/Version.java
validation/pom.xml
validation/src/main/java/org/craftercms/commons/validation/annotations/param/EsapiValidatedParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/SqlSort.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidConfigurationPath.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidExistingContentPath.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidNewContentPath.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidSiteId.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidUsername.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateNoTagsParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateSecurePathParam.java
validation/src/main/java/org/craftercms/commons/validation/annotations/param/ValidateStringParam.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/AbstractStringValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/EsapiValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/NoTagsValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/SecurePathValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/SortFieldValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/SqlSortValidator.java
validation/src/main/java/org/craftercms/commons/validation/validators/impl/StringValidator.java

https://github.com/craftercms/craftercms/issues/5977

Update to use jakarta.validation

---

validation/src/main/resources/esapi/ESAPI.properties
validation/src/test/java/org/craftercms/commons/validation/validators/impl/EmailAddressTest.java

https://github.com/craftercms/craftercms/issues/6645

Update email regex according RFC 5322

---

utilities/pom.xml
utilities/src/main/java/org/craftercms/commons/aws/AbstractAwsClientCachingFactory.java
utilities/src/main/java/org/craftercms/commons/aws/AwsUtils.java
utilities/src/main/java/org/craftercms/commons/aws/S3AsyncClientCachingFactory.java
utilities/src/main/java/org/craftercms/commons/aws/S3ClientCachingFactory.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfile.java
utilities/src/main/java/org/craftercms/commons/config/profiles/aws/AbstractAwsProfileMapper.java
utilities/src/main/java/org/craftercms/commons/file/blob/impl/s3/AwsS3BlobStore.java
utilities/src/main/java/org/craftercms/commons/file/stores/S3Utils.java
utilities/src/main/java/org/craftercms/commons/http/HttpUtils.java
utilities/src/main/java/org/craftercms/commons/spring/resources/S3Resource.java
utilities/src/test/java/org/craftercms/commons/aws/AwsUtilsTest.java
utilities/src/test/java/org/craftercms/commons/config/EncryptionAwareConfigurationReaderTest.java
utilities/src/test/java/org/craftercms/commons/http/HttpUtilsTest.java

https://github.com/craftercms/craftercms/issues/6617

Upgrade to AWS SDK v2

---

utilities/src/main/java/org/craftercms/commons/aws/AwsUtils.java

https://github.com/craftercms/craftercms/issues/6766
Publisher updates support

Support error/completion report in AWS copy
